# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='foo',
        ),
        migrations.RemoveField(
            model_name='child',
            name='parent_ptr',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
